name: Build and push packages

on:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: 'flowforge/github-actions-workflows/.github/workflows/build_node_package.yml@main'

  publish:
    needs: build
    uses: 'flowforge/github-actions-workflows/.github/workflows/publish_node_package.yml@fix-publish-with-npm'
    with:
      package_name: nr-persistent-context
      publish_package: true

  directPublish:
    if: false
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set release name
        id: set_release_name
        run: |
          echo "release_name=nightly" >> $GITHUB_ENV

      - name: "Set package version"
        run: |
          npm version prerelease --preid `git rev-parse --short HEAD`-`date +%Y%m%d` --no-git-tag-version

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
          scope: '@flowforge'
          always-auth: true

      - run: npm publish --ignore-scripts --tag 'nightly'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
